const ListOfProducts = {
    food : [
    {
        id:1,
        name:'Muzzarella',
        type:'pizzas',
        size:'1 Mtrs',
        price:2000,
        amount:0,
        img: "/img/img_pizzas/muzzarella.jpg",
    },
    {
        id:2,
        name:'Napolitana',
        type:'pizzas',
        size:'Grande',
        price:2000,
        amount:0,
        img: "/img/img_pizzas/napolitana.jpg",
    },
    {
        id:3,
        name:'Jamón y morrones',
        type:'pizzas',
        size:'Pequeña',
        price:800,
        amount:0,
        img: "/img/img_pizzas/jamonymorron.webp",
    },
    {
        id:4,
        name:'Empanadas de carne',
        type:'empanadas',
        size:'standard',
        price:2000,
        amount:0,
        img: "/img/img_empanadas/empanada_carne.jpg",
    },
    {
        id:5,
        name:'Empanadas de jamón y queso',
        type:'empanadas',
        size:'standard',
        price:2000,
        amount:0,
        img: "/img/img_empanadas/empanada_jamonyqueso.jpg",
    },
    {
        id:6,
        name:'Empanadas de atún',
        type:'empanadas',
        size:'standard',
        price:2000,
        amount:0,
        img: "/img/img_empanadas/empanada_atun.jpg",
    },
    {
        id:7,
        name:'Coca Cola 2.5Lts',
        type:'bebidas',
        size:'2.5 Lts',
        price:1000,
        amount:0,
        img: "/img/img_bebidas/gaseosa.jpg",
    },
    {
        id:8,
        name:'Agua',
        type:'bebidas',
        size:'2.5 Lts',
        price:1000,
        amount:0,
        img: "/img/img_bebidas/agua.jpg",
    },
    {
        id:9,
        name:'Cerveza',
        type:'bebidas',
        size:'1 Lts',
        price:1200,
        amount:0,
        img: "/img/img_bebidas/cerveza.jpg",
    },
    {
        id:10,
        name:'Almendrado',
        type:'postres',
        size:'1 Kgs',
        price:2000,
        amount:0,
        img: "/img/img_postres/almendrado.jpg",
    },
    {
        id:11,
        name:'helado',
        type:'postres',
        size:'1 unidad',
        price:2000,
        amount:0,
        img: "/img/img_postres/helado.jpg",
    },
    {
        id:12,
        name:'Bombones',
        type:'postres',
        size:'100 Grs',
        price:2000,
        amount:0,
        img: "/img/img_postres/bombones.jpg",
    },
    {
        id:13,
        name:'faina',
        type:'fainas',
        size:'1 rebanada',
        price:2000,
        amount:0,
        img: "/img/logo.jpg",
    },
]
};

export default ListOfProducts;